# Example: Deploy to Staging with n8n notifications
# Copy this file to .github/workflows/deploy-staging.yml in your project

name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify n8n - Deploy Started
        run: |
          curl -s -X POST ${{ secrets.N8N_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "event_type": "deploy",
              "status": "started",
              "project": {
                "id": "your-project-id",
                "name": "Your Project Name"
              },
              "environment": "staging",
              "actor": {
                "github_username": "${{ github.actor }}"
              },
              "commit": {
                "sha": "${{ github.sha }}",
                "message": "${{ github.event.head_commit.message }}",
                "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
              },
              "pipeline": {
                "id": "${{ github.run_id }}",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }'

      # ===========================================
      # YOUR DEPLOYMENT STEPS HERE
      # ===========================================
      - name: Deploy
        run: |
          echo "Add your deployment commands here"
          # Examples:
          # - npm run build && npm run deploy
          # - railway up --environment staging
          # - aws s3 sync ./dist s3://your-bucket
          # - kubectl apply -f k8s/staging/

      - name: Notify n8n - Deploy Success
        if: success()
        run: |
          curl -s -X POST ${{ secrets.N8N_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "event_type": "deploy",
              "status": "success",
              "project": {
                "id": "your-project-id",
                "name": "Your Project Name"
              },
              "environment": "staging",
              "actor": {
                "github_username": "${{ github.actor }}"
              },
              "commit": {
                "sha": "${{ github.sha }}",
                "message": "${{ github.event.head_commit.message }}",
                "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
              },
              "pipeline": {
                "id": "${{ github.run_id }}",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }'

      - name: Notify n8n - Deploy Failed
        if: failure()
        run: |
          curl -s -X POST ${{ secrets.N8N_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "event_type": "deploy",
              "status": "failed",
              "project": {
                "id": "your-project-id",
                "name": "Your Project Name"
              },
              "environment": "staging",
              "actor": {
                "github_username": "${{ github.actor }}"
              },
              "commit": {
                "sha": "${{ github.sha }}",
                "message": "${{ github.event.head_commit.message }}",
                "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
              },
              "pipeline": {
                "id": "${{ github.run_id }}",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            }'
